// Seed data for TechZone
// All images point at locally generated SVGs in client/public/images/products/
// so the store never depends on a fragile external image host.

const IMG = (slug) => `/images/products/${slug}.svg`;

const products = [
  {
    name: 'TechZone Phantom X Gaming Laptop',
    brand: 'TechZone',
    category: 'Laptops',
    price: 134999,
    originalPrice: 149999,
    rating: 4.8,
    numReviews: 214,
    stock: 12,
    isFeatured: true,
    isTrending: true,
    images: [IMG('phantom-x-laptop')],
    description:
      'The Phantom X is our flagship gaming beast — a 16-inch QHD+ 240Hz display wrapped around an Intel Core i9 processor and NVIDIA RTX 4080 graphics. Vapor-chamber cooling keeps every frame clean while the per-key RGB keyboard keeps your setup looking future-forward. Built for competitive gamers who refuse to compromise.',
    specifications: [
      { label: 'Processor', value: 'Intel Core i9-13980HX' },
      { label: 'Graphics', value: 'NVIDIA RTX 4080 12GB GDDR6' },
      { label: 'RAM', value: '32GB DDR5 5600MHz' },
      { label: 'Storage', value: '2TB NVMe Gen4 SSD' },
      { label: 'Display', value: '16" QHD+ 2560×1600, 240Hz' },
      { label: 'Connectivity', value: 'Wi-Fi 6E / Bluetooth 5.3' },
      { label: 'Battery', value: '90Wh, 330W adapter' },
      { label: 'Weight', value: '2.4 kg' },
    ],
  },
  {
    name: 'TechZone Core Gaming Laptop',
    brand: 'TechZone',
    category: 'Laptops',
    price: 89999,
    originalPrice: 99999,
    rating: 4.6,
    numReviews: 168,
    stock: 15,
    isTrending: true,
    images: [IMG('core-gaming-laptop')],
    description:
      'Serious gaming power at a smarter price. The Core pairs a 13th-gen Intel i7 with RTX 4060 graphics and a 144Hz display, tuned by TechZone engineers for high-FPS esports titles. Dual-fan cooling and a full-sized RGB keyboard make it the perfect first battlestation.',
    specifications: [
      { label: 'Processor', value: 'Intel Core i7-13650HX' },
      { label: 'Graphics', value: 'NVIDIA RTX 4060 8GB' },
      { label: 'RAM', value: '16GB DDR5' },
      { label: 'Storage', value: '1TB NVMe SSD' },
      { label: 'Display', value: '15.6" FHD 144Hz IPS' },
      { label: 'Connectivity', value: 'Wi-Fi 6 / Bluetooth 5.2' },
      { label: 'Battery', value: '57Wh fast-charge' },
    ],
  },
  {
    name: 'TechZone Vega Creator Laptop',
    brand: 'TechZone',
    category: 'Laptops',
    price: 104999,
    originalPrice: 114999,
    rating: 4.7,
    numReviews: 96,
    stock: 10,
    isFeatured: true,
    images: [IMG('vega-creator-laptop')],
    description:
      'Designed for creators who render, edit and stream. The Vega packs an RTX 4070 into a precision-machined chassis with a 100% DCI-P3 color-accurate panel. Studio-grade acoustics and a whisper-quiet performance mode make it as comfortable in a café as on a film set.',
    specifications: [
      { label: 'Processor', value: 'Intel Core i7-13700H' },
      { label: 'Graphics', value: 'NVIDIA RTX 4070 8GB' },
      { label: 'RAM', value: '32GB DDR5' },
      { label: 'Storage', value: '1TB NVMe Gen4 SSD' },
      { label: 'Display', value: '16" 2.5K 165Hz, 100% DCI-P3' },
      { label: 'Connectivity', value: 'Wi-Fi 6E / Bluetooth 5.3' },
      { label: 'Weight', value: '1.9 kg' },
    ],
  },
  {
    name: 'TechZone ProBook 15',
    brand: 'TechZone',
    category: 'Laptops',
    price: 54999,
    originalPrice: 62999,
    rating: 4.5,
    numReviews: 231,
    stock: 24,
    images: [IMG('probook-15')],
    description:
      'All-day productivity in a 1.6 kg aluminum body. The ProBook 15 handles classes, code and conferences with a 13th-gen i5, 16GB of RAM and a color-rich FHD display. An 18-hour battery and fingerprint login keep your workflow moving anywhere.',
    specifications: [
      { label: 'Processor', value: 'Intel Core i5-1335U' },
      { label: 'RAM', value: '16GB DDR4' },
      { label: 'Storage', value: '512GB NVMe SSD' },
      { label: 'Display', value: '15.6" FHD IPS anti-glare' },
      { label: 'Battery', value: 'Up to 18 hours' },
      { label: 'Connectivity', value: 'Wi-Fi 6 / Bluetooth 5.2' },
      { label: 'Weight', value: '1.6 kg' },
    ],
  },
  {
    name: 'RGB Mechanical Keyboard',
    brand: 'Apexis',
    category: 'Keyboards',
    price: 6499,
    originalPrice: 8999,
    rating: 4.7,
    numReviews: 312,
    stock: 42,
    isTrending: true,
    images: [IMG('rgb-mechanical-keyboard')],
    description:
      'A full-size mechanical keyboard with per-key RGB, hot-swappable switches and double-shot PBT keycaps. A gasket-mounted design delivers a deep, satisfying typing sound while 100% anti-ghosting keeps every command registered in the heat of battle.',
    specifications: [
      { label: 'Switches', value: 'Hot-swappable Red (linear)' },
      { label: 'Keycaps', value: 'Double-shot PBT' },
      { label: 'Lighting', value: 'Per-key RGB, 20 effects' },
      { label: 'Layout', value: 'Full-size 104-key' },
      { label: 'Connection', value: 'Detachable USB-C' },
      { label: 'Polling Rate', value: '1000Hz' },
    ],
  },
  {
    name: 'TKL Mechanical Keyboard',
    brand: 'Apexis',
    category: 'Keyboards',
    price: 4299,
    originalPrice: null,
    rating: 4.4,
    numReviews: 147,
    stock: 35,
    images: [IMG('tkl-mechanical-keyboard')],
    description:
      'The tenkeyless layout frees up desk space without sacrificing the feel. Tactile brown switches, an aluminum top plate and pure white backlighting make this the clean, focused board for work and play.',
    specifications: [
      { label: 'Switches', value: 'Tactile Brown' },
      { label: 'Layout', value: 'Tenkeyless 87-key' },
      { label: 'Lighting', value: 'White LED, 8 effects' },
      { label: 'Keycaps', value: 'PBT dye-sublimated' },
      { label: 'Connection', value: 'Braided USB-A' },
    ],
  },
  {
    name: 'Wireless Gaming Mouse',
    brand: 'Vortex',
    category: 'Gaming',
    price: 3499,
    originalPrice: 4999,
    rating: 4.6,
    numReviews: 265,
    stock: 58,
    isTrending: true,
    images: [IMG('wireless-gaming-mouse')],
    description:
      'At 58 grams with a 26,000 DPI optical sensor and 400-hour battery, the Vortex wireless mouse disappears in your hand and reappears on the scoreboard. Ultra-low-latency 2.4GHz wireless with Bluetooth and USB-C wired modes.',
    specifications: [
      { label: 'Sensor', value: '26,000 DPI optical' },
      { label: 'Weight', value: '58 g' },
      { label: 'Battery', value: 'Up to 400 hours' },
      { label: 'Connection', value: '2.4GHz / Bluetooth / USB-C' },
      { label: 'Switches', value: '90M-click mechanical' },
    ],
  },
  {
    name: 'Gaming Headset',
    brand: 'SonicForge',
    category: 'Audio',
    price: 5999,
    originalPrice: 7499,
    rating: 4.5,
    numReviews: 198,
    stock: 30,
    isTrending: true,
    images: [IMG('gaming-headset')],
    description:
      'Hear every footstep with virtual 7.1 surround and 50mm drivers tuned for competitive play. The AI noise-canceling boom mic keeps your callouts crystal clear, and memory-foam earcups stay cool through marathon sessions.',
    specifications: [
      { label: 'Drivers', value: '50mm neodymium' },
      { label: 'Surround', value: 'Virtual 7.1' },
      { label: 'Microphone', value: 'Detachable, AI noise-cancel' },
      { label: 'Connection', value: 'USB + 3.5mm' },
      { label: 'Comfort', value: 'Memory foam, suspension headband' },
    ],
  },
  {
    name: 'ANC Headphones',
    brand: 'AuraSound',
    category: 'Audio',
    price: 12999,
    originalPrice: 15999,
    rating: 4.8,
    numReviews: 421,
    stock: 22,
    isFeatured: true,
    images: [IMG('anc-headphones')],
    description:
      'Flagship hybrid noise cancellation silences up to 42dB of the world while custom 40mm drivers deliver rich, detailed sound. Forty hours of playback, multipoint pairing and a luxe travel case — engineered for focus anywhere.',
    specifications: [
      { label: 'Noise Canceling', value: 'Hybrid ANC, up to 42dB' },
      { label: 'Drivers', value: '40mm custom dynamic' },
      { label: 'Battery', value: '40h (ANC on), USB-C fast charge' },
      { label: 'Bluetooth', value: '5.3 with multipoint' },
      { label: 'Codecs', value: 'LDAC / AAC / SBC' },
      { label: 'Weight', value: '252 g' },
    ],
  },
  {
    name: 'Wireless Earbuds',
    brand: 'AuraSound',
    category: 'Audio',
    price: 4999,
    originalPrice: 6999,
    rating: 4.4,
    numReviews: 508,
    stock: 65,
    isTrending: true,
    images: [IMG('wireless-earbuds')],
    description:
      'Compact ANC earbuds with a 36-hour total battery, wireless charging case and crystal-clear call quality. IPX5 sweat resistance and an ultra-low 60ms game mode make them as versatile as your day.',
    specifications: [
      { label: 'Noise Canceling', value: 'Active ANC, 28dB' },
      { label: 'Battery', value: '8h buds + 28h case' },
      { label: 'Charging', value: 'USB-C + wireless' },
      { label: 'Game Mode', value: '60ms low latency' },
      { label: 'Water Resistance', value: 'IPX5' },
    ],
  },
  {
    name: 'Streaming Microphone',
    brand: 'Clario',
    category: 'Audio',
    price: 6999,
    originalPrice: 8499,
    rating: 4.6,
    numReviews: 133,
    stock: 25,
    isFeatured: true,
    images: [IMG('streaming-microphone')],
    description:
      'A studio-grade USB-C condenser with four pickup patterns, a tap-to-mute sensor and zero-latency monitoring. Cardioid, stereo, omnidirectional and bi-directional modes cover streaming, podcasting and recording in one sleek package.',
    specifications: [
      { label: 'Capsule', value: '14mm condenser' },
      { label: 'Pickup Patterns', value: 'Cardioid / Bi-dir / Omni / Stereo' },
      { label: 'Sample Rate', value: '24-bit / 96kHz' },
      { label: 'Extras', value: 'Tap-to-mute, headphone monitoring' },
      { label: 'Connection', value: 'USB-C' },
    ],
  },
  {
    name: 'Bluetooth Speaker',
    brand: 'AuraSound',
    category: 'Audio',
    price: 3499,
    originalPrice: 4299,
    rating: 4.3,
    numReviews: 176,
    stock: 50,
    images: [IMG('bluetooth-speaker')],
    description:
      '20 watts of 360° sound in a rugged IPX7 body that floats. Pair two for true stereo, get 24 hours of playback and take calls with the built-in speakerphone. Built for pools, trails and impromptu dance floors.',
    specifications: [
      { label: 'Output', value: '20W 360° sound' },
      { label: 'Battery', value: '24 hours' },
      { label: 'Water Resistance', value: 'IPX7 waterproof, floats' },
      { label: 'Pairing', value: 'Stereo pairing (2 speakers)' },
      { label: 'Bluetooth', value: '5.3, 30m range' },
    ],
  },
  {
    name: '27-inch 144Hz Monitor',
    brand: 'NovaView',
    category: 'Monitors',
    price: 21999,
    originalPrice: 25999,
    rating: 4.6,
    numReviews: 189,
    stock: 18,
    isTrending: true,
    images: [IMG('monitor-27-144hz')],
    description:
      'A QHD IPS panel with 144Hz, 1ms (GtG) response and 95% DCI-P3 color. Height-adjustable ergonomic stand, HDR400 support and adaptive-sync make this the sweet-spot display for gaming and creation alike.',
    specifications: [
      { label: 'Panel', value: '27" IPS QHD 2560×1440' },
      { label: 'Refresh Rate', value: '144Hz' },
      { label: 'Response', value: '1ms GtG' },
      { label: 'Color', value: '95% DCI-P3, HDR400' },
      { label: 'Ports', value: '2× HDMI 2.0, DisplayPort 1.4' },
      { label: 'Ergonomics', value: 'Height / tilt / pivot / swivel' },
    ],
  },
  {
    name: '24-inch Productivity Monitor',
    brand: 'NovaView',
    category: 'Monitors',
    price: 9999,
    originalPrice: 11999,
    rating: 4.3,
    numReviews: 142,
    stock: 26,
    images: [IMG('monitor-24-office')],
    description:
      'A clean, flicker-free FHD IPS display built for long work sessions. 75Hz, thin bezels on three sides and a built-in USB hub with cable management keep your desk minimal and your eyes comfortable.',
    specifications: [
      { label: 'Panel', value: '24" IPS FHD 1920×1080' },
      { label: 'Refresh Rate', value: '75Hz' },
      { label: 'Comfort', value: 'Flicker-free, low blue light' },
      { label: 'Ports', value: 'HDMI, VGA, USB hub' },
      { label: 'Mount', value: 'VESA 100×100' },
    ],
  },
  {
    name: 'Ultrawide Curved Monitor 34"',
    brand: 'NovaView',
    category: 'Monitors',
    price: 38999,
    originalPrice: 44999,
    rating: 4.7,
    numReviews: 87,
    stock: 9,
    isFeatured: true,
    images: [IMG('monitor-34-ultrawide')],
    description:
      'A 34-inch WQHD curved canvas that replaces your dual-monitor setup. 165Hz, 1000R curvature and a built-in KVM switch let one keyboard glide between your PC and console. Cinematic for games, devastating for spreadsheets.',
    specifications: [
      { label: 'Panel', value: '34" VA WQHD 3440×1440' },
      { label: 'Curvature', value: '1000R' },
      { label: 'Refresh Rate', value: '165Hz' },
      { label: 'Features', value: 'Built-in KVM, Picture-by-Picture' },
      { label: 'Ports', value: '2× HDMI 2.1, DP 1.4, USB-C 65W' },
    ],
  },
  {
    name: 'Gaming Controller',
    brand: 'Vortex',
    category: 'Gaming',
    price: 4999,
    originalPrice: 5999,
    rating: 4.5,
    numReviews: 154,
    stock: 38,
    images: [IMG('gaming-controller')],
    description:
      'Hall-effect sticks that never drift, anti-friction rings and rear paddles in a pro-weight shell. Play wired or wireless on PC, with remappable buttons and three on-board profiles saved to the controller.',
    specifications: [
      { label: 'Sticks', value: 'Hall-effect (zero drift)' },
      { label: 'Triggers', value: 'Hair-trigger mode' },
      { label: 'Profiles', value: '3 on-board, remappable' },
      { label: 'Connection', value: '2.4GHz dongle / USB-C' },
      { label: 'Compatibility', value: 'Windows PC' },
    ],
  },
  {
    name: 'Gaming Mousepad XL',
    brand: 'Vortex',
    category: 'Gaming',
    price: 1299,
    originalPrice: 1699,
    rating: 4.6,
    numReviews: 289,
    stock: 90,
    images: [IMG('gaming-mousepad-xl')],
    description:
      'A 900×400mm micro-weave surface for pixel-precise glides, with a stitched anti-fray edge and non-slip rubber base. Subtle edge lighting gives your desk a premium glow without the rainbow circus.',
    specifications: [
      { label: 'Size', value: '900 × 400 × 4 mm' },
      { label: 'Surface', value: 'Micro-weave cloth' },
      { label: 'Base', value: 'Anti-slip rubber' },
      { label: 'Edge', value: 'Stitched anti-fray' },
    ],
  },
  {
    name: 'USB-C GaN Charger 100W',
    brand: 'VoltEdge',
    category: 'Accessories',
    price: 2999,
    originalPrice: 3999,
    rating: 4.6,
    numReviews: 344,
    stock: 80,
    images: [IMG('gan-charger-100w')],
    description:
      'GaN III tech shrinks a 100W desktop brick into a pocket-sized cube. Three ports intelligently share power to fast-charge a laptop, phone and earbuds at the same time — with foldable pins and worldwide voltage.',
    specifications: [
      { label: 'Power', value: '100W max (PD 3.1)' },
      { label: 'Ports', value: '2× USB-C, 1× USB-A' },
      { label: 'Technology', value: 'GaN III' },
      { label: 'Size', value: 'Pocketable, foldable pins' },
      { label: 'Safety', value: 'Over-current & thermal protection' },
    ],
  },
  {
    name: 'USB-C Hub 8-in-1',
    brand: 'VoltEdge',
    category: 'Accessories',
    price: 3499,
    originalPrice: null,
    rating: 4.4,
    numReviews: 211,
    stock: 47,
    images: [IMG('usbc-hub-8in1')],
    description:
      'Turn one USB-C port into a full workstation: 4K@60Hz HDMI, 100W power delivery passthrough, gigabit ethernet, SD/microSD and three USB-A ports. An aluminum shell doubles as the heat sink.',
    specifications: [
      { label: 'Video', value: 'HDMI 4K@60Hz' },
      { label: 'Power', value: '100W PD passthrough' },
      { label: 'Network', value: 'Gigabit Ethernet' },
      { label: 'Cards', value: 'SD + microSD (UHS-I)' },
      { label: 'USB', value: '3× USB-A 3.0' },
    ],
  },
  {
    name: 'Multi-Port Adapter',
    brand: 'VoltEdge',
    category: 'Accessories',
    price: 1999,
    originalPrice: null,
    rating: 4.1,
    numReviews: 98,
    stock: 36,
    images: [IMG('multiport-adapter')],
    description:
      'The travel essential: HDMI up to 4K@30Hz, VGA for projectors, gigabit LAN, a USB-C data port and two USB-A ports in one pocket-sized adapter. Plug-and-play on Windows, macOS and Linux.',
    specifications: [
      { label: 'Video', value: 'HDMI 4K@30Hz + VGA 1080p' },
      { label: 'Network', value: 'Gigabit Ethernet' },
      { label: 'USB', value: '2× USB-A 3.0, 1× USB-C data' },
      { label: 'OS Support', value: 'Windows / macOS / Linux' },
    ],
  },
  {
    name: 'Braided USB-C Cable 2m',
    brand: 'VoltEdge',
    category: 'Accessories',
    price: 799,
    originalPrice: 999,
    rating: 4.5,
    numReviews: 412,
    stock: 120,
    images: [IMG('usbc-cable-2m')],
    description:
      'A 100W, 480Mbps USB 2.0 cable with a 30,000-bend nylon braid and reinforced aluminum housings. The cable you buy once and keep for years — with right-angle options that spare your phone’s port.',
    specifications: [
      { label: 'Length', value: '2 meters' },
      { label: 'Power', value: '100W (5A) USB-C PD' },
      { label: 'Data', value: '480 Mbps' },
      { label: 'Build', value: 'Nylon braid, 30,000-bend rated' },
    ],
  },
  {
    name: 'Full HD Webcam',
    brand: 'Clario',
    category: 'Accessories',
    price: 2799,
    originalPrice: 3499,
    rating: 4.2,
    numReviews: 167,
    stock: 44,
    images: [IMG('webcam-fhd')],
    description:
      'Sharp 1080p60 video with auto-light correction, dual noise-canceling mics and a privacy shutter. The adjustable clip mounts on any monitor or tripod, and the glass lens keeps you looking human on every call.',
    specifications: [
      { label: 'Video', value: '1080p @ 60fps' },
      { label: 'Lens', value: 'Glass, 78° FOV' },
      { label: 'Lighting', value: 'Auto light correction' },
      { label: 'Microphones', value: 'Dual noise-canceling' },
      { label: 'Extras', value: 'Privacy shutter, tripod thread' },
    ],
  },
  {
    name: 'Laptop Stand',
    brand: 'ErgoFlow',
    category: 'Accessories',
    price: 1899,
    originalPrice: 2499,
    rating: 4.4,
    numReviews: 203,
    stock: 60,
    images: [IMG('laptop-stand')],
    description:
      'A CNC aluminum stand that raises your laptop 6 inches for a healthier neck, with open sides for airflow and silicone pads that grip without scratching. Folds flat into any backpack.',
    specifications: [
      { label: 'Material', value: 'CNC aluminum' },
      { label: 'Height', value: '6-inch raise' },
      { label: 'Compatibility', value: '10–17" laptops' },
      { label: 'Features', value: 'Foldable, silicone grip pads' },
    ],
  },
  {
    name: '1TB External SSD',
    brand: 'HyperStore',
    category: 'Components',
    price: 7499,
    originalPrice: 8999,
    rating: 4.7,
    numReviews: 376,
    stock: 54,
    isTrending: true,
    images: [IMG('external-ssd-1tb')],
    description:
      'Transfer speeds up to 1050MB/s in a shockproof, pocket-sized shell smaller than a card deck. USB-C out of the box, hardware AES-256 encryption, and three years of password recovery included.',
    specifications: [
      { label: 'Capacity', value: '1TB' },
      { label: 'Speed', value: 'Up to 1050 MB/s read' },
      { label: 'Interface', value: 'USB 3.2 Gen2 (USB-C)' },
      { label: 'Durability', value: '2m drop-resistant' },
      { label: 'Security', value: 'AES-256 hardware encryption' },
    ],
  },
  {
    name: '2TB NVMe Internal SSD',
    brand: 'HyperStore',
    category: 'Components',
    price: 11999,
    originalPrice: 13999,
    rating: 4.8,
    numReviews: 265,
    stock: 33,
    images: [IMG('nvme-ssd-2tb')],
    description:
      'PCIe 4.0 speeds up to 7000MB/s slash load times and compile queues. A slim graphene heat spreader keeps thermals in check, and 1200 TBW endurance is backed by a 5-year warranty.',
    specifications: [
      { label: 'Capacity', value: '2TB' },
      { label: 'Speed', value: '7000/6000 MB/s R/W' },
      { label: 'Interface', value: 'PCIe 4.0 ×4 NVMe 2.0' },
      { label: 'Endurance', value: '1200 TBW' },
      { label: 'Warranty', value: '5 years' },
    ],
  },
  {
    name: '16GB DDR5 RAM Kit',
    brand: 'HyperStore',
    category: 'Components',
    price: 5499,
    originalPrice: 6499,
    rating: 4.5,
    numReviews: 128,
    stock: 40,
    images: [IMG('ddr5-ram-16gb')],
    description:
      'A 2×8GB DDR5-5600 kit with low 36-36-36-76 timings, sleek aluminum heat spreaders and onboard PMIC for stable power. XMP 3.0 profiles overclock in one click.',
    specifications: [
      { label: 'Capacity', value: '16GB (2×8GB)' },
      { label: 'Speed', value: 'DDR5-5600' },
      { label: 'Timings', value: 'CL36-36-36-76' },
      { label: 'Voltage', value: '1.25V' },
      { label: 'Profiles', value: 'Intel XMP 3.0 / AMD EXPO' },
    ],
  },
];

const users = [
  {
    name: 'Arjun Mehta',
    email: 'user@techzone.com',
    password: 'User@123',
    role: 'user',
  },
  {
    name: 'Priya Sharma',
    email: 'priya@example.com',
    password: 'User@123',
    role: 'user',
  },
];

module.exports = { products, users };
